### PR TITLE
Update build instructions in the README file

### PR DESCRIPTION
**Pull request by h3nr1ke**
Hello,

this will add more information to build the documentation. I tried it my self in a fresh mint installation.

Hope it helps other to build and contribute

this PR address the issue #4

### CODE REVIEW

**Comment by mtwebster** [comment]
I'm really not crazy about providing pip instructions here - mixing pip packages with system packages can cause broken apps.

We can remove it, or maybe a firm warning for the pip instructions to only do this in a virtual environment.

**Comment by h3nr1ke** [comment]
Hey @mtwebster thanks for taking time to review it

What about add ths disclaimer like this one

> Alternatively, you can use pip3 to complete the process, but pay attention that this should be done only if you are in a virtual environment.

What to do you think?

**Comment by mtwebster** [comment]
Sorry, missed your response, that's fine

**Comment by h3nr1ke** [comment]
Hey @mtwebster, no problem

I just did the update =)

**Pull request merged**
